language: bash
sudo: required

services:
  - docker

env:
  - version: 0c9d7eb56c9d4aa86f01f26937f777a17590c8da
  # - version: v3.0.0
  # - version: v3.2.0
  # - version: v3.3.0
  # - version: v3.3.1
  # - version: v3.3.2
  # - version: master

before_install: 
  - docker build --build-arg citydb_wfs_version=${version} -t tumgis/3dcitydb-wfs:${version} .

before_script:
  - docker run --name cdb -d tumgis/3dcitydb-postgis:latest-alpine

script:
  - sleep 30
  - docker run --name wfs -d -p 8765:8080 --link "cdb:cdb" -e "CITYDB_CONNECTION_SERVER=cdb" tumgis/3dcitydb-wfs:${version}
  - sleep 10
  - docker logs wfs
  - curl "http://127.0.0.1:8765/citydb-wfs/wfs?SERVICE=WFS&REQUEST=GetCapabilities"
  
  # - docker logs ${version} | grep -Pzl "(?s)Setting up 3DCityDB ... done!.*database system is ready to accept connections"
  # - docker logs ${version}-alpine | grep -Pzl "(?s)Setting up 3DCityDB ... done!.*database system is ready to accept connections"
  
  
notifications:
    slack: tum-gis:Z32lHXJDXaycOn4643NHSXaT
    on_success: change
    on_failure: always
